import { Router, type IRouter } from "express";
import healthRouter from "./health";
import attacksRouter from "./attacks";
import methodsRouter from "./methods";
import checkRouter from "./check";
import analyzeRouter from "./analyze";
import proxiesRouter from "./proxies";
import originFinderRouter from "./origin-finder";
import clusterRouter from "./cluster";
import eventsRouter from "./events";
import imageRouter from "./image";
import queryRouter from "./query";
import checkerRouter from "./checker";
import credentialsRouter from "./credentials";
import dnsRouter from "./dns";
import discordRouter from "./discord";
import nitroRouter from "./nitro";
import skynetchatRouter from "./skynetchat";
import whatsappRouter from "./whatsapp";
import socialRouter    from "./social";
import usersRouter     from "./users";
import infinityRouter  from "./infinity";
import infinityPaymentsRouter from "./infinity-payments";
import infinityWalletRouter from "./infinity-wallet";
import infinityAffiliateRouter from "./infinity-affiliate";
import infinitySocialRouter from "./infinity-social";

const router: IRouter = Router();

router.use(healthRouter);
router.use(eventsRouter);
router.use(attacksRouter);
router.use(methodsRouter);
router.use(checkRouter);
router.use(analyzeRouter);
router.use(proxiesRouter);
router.use(originFinderRouter);
router.use(clusterRouter);
router.use(imageRouter);
router.use(queryRouter);
router.use(checkerRouter);
router.use("/credentials", credentialsRouter);
router.use(dnsRouter);
router.use(discordRouter);
router.use(nitroRouter);
router.use(skynetchatRouter);
router.use("/whatsapp", whatsappRouter);
router.use("/social",  socialRouter);
router.use("/users",   usersRouter);
router.use("/infinity", infinityRouter);
router.use("/infinity", infinityPaymentsRouter);
router.use("/infinity", infinityWalletRouter);
router.use("/infinity", infinityAffiliateRouter);
router.use("/infinity", infinitySocialRouter);

export default router;
